/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsPostId = IDL.Nat;
export const Time = IDL.Int;
export const NewsCategory = IDL.Variant({
  'teamNews' : IDL.Null,
  'gameRecap' : IDL.Null,
  'announcement' : IDL.Null,
  'leagueUpdate' : IDL.Null,
});
export const NewsPost = IDL.Record({
  'id' : NewsPostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : Time,
  'author' : IDL.Text,
  'category' : NewsCategory,
});
export const GameId = IDL.Nat;
export const GameStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TeamId = IDL.Nat;
export const Game = IDL.Record({
  'id' : GameId,
  'status' : GameStatus,
  'awayTeamId' : TeamId,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'week' : IDL.Nat,
  'homeTeamId' : TeamId,
  'season' : IDL.Nat,
  'homeScore' : IDL.Opt(IDL.Nat),
  'awayScore' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
});
export const Team = IDL.Record({
  'id' : TeamId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'ties' : IDL.Nat,
  'wins' : IDL.Nat,
  'division' : IDL.Text,
  'losses' : IDL.Nat,
  'colors' : IDL.Record({ 'secondary' : IDL.Text, 'primary' : IDL.Text }),
});
export const Standing = IDL.Record({
  'pointsFor' : IDL.Nat,
  'ties' : IDL.Nat,
  'wins' : IDL.Nat,
  'conferenceRank' : IDL.Nat,
  'division' : IDL.Text,
  'losses' : IDL.Nat,
  'pointsAgainst' : IDL.Nat,
  'teamId' : TeamId,
});

export const idlService = IDL.Service({
  'addNewsPost' : IDL.Func([NewsPost], [], []),
  'addUpdateGame' : IDL.Func([Game], [], []),
  'addUpdateTeam' : IDL.Func([Team], [], []),
  'getCompletedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getNewsPost' : IDL.Func([NewsPostId], [NewsPost], ['query']),
  'getStandings' : IDL.Func([], [IDL.Vec(Standing)], ['query']),
  'getTeam' : IDL.Func([TeamId], [Team], ['query']),
  'getTeamGames' : IDL.Func([TeamId], [IDL.Vec(Game)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getUpcomingGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsPostId = IDL.Nat;
  const Time = IDL.Int;
  const NewsCategory = IDL.Variant({
    'teamNews' : IDL.Null,
    'gameRecap' : IDL.Null,
    'announcement' : IDL.Null,
    'leagueUpdate' : IDL.Null,
  });
  const NewsPost = IDL.Record({
    'id' : NewsPostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : Time,
    'author' : IDL.Text,
    'category' : NewsCategory,
  });
  const GameId = IDL.Nat;
  const GameStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TeamId = IDL.Nat;
  const Game = IDL.Record({
    'id' : GameId,
    'status' : GameStatus,
    'awayTeamId' : TeamId,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'week' : IDL.Nat,
    'homeTeamId' : TeamId,
    'season' : IDL.Nat,
    'homeScore' : IDL.Opt(IDL.Nat),
    'awayScore' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
  });
  const Team = IDL.Record({
    'id' : TeamId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'ties' : IDL.Nat,
    'wins' : IDL.Nat,
    'division' : IDL.Text,
    'losses' : IDL.Nat,
    'colors' : IDL.Record({ 'secondary' : IDL.Text, 'primary' : IDL.Text }),
  });
  const Standing = IDL.Record({
    'pointsFor' : IDL.Nat,
    'ties' : IDL.Nat,
    'wins' : IDL.Nat,
    'conferenceRank' : IDL.Nat,
    'division' : IDL.Text,
    'losses' : IDL.Nat,
    'pointsAgainst' : IDL.Nat,
    'teamId' : TeamId,
  });
  
  return IDL.Service({
    'addNewsPost' : IDL.Func([NewsPost], [], []),
    'addUpdateGame' : IDL.Func([Game], [], []),
    'addUpdateTeam' : IDL.Func([Team], [], []),
    'getCompletedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getNewsPost' : IDL.Func([NewsPostId], [NewsPost], ['query']),
    'getStandings' : IDL.Func([], [IDL.Vec(Standing)], ['query']),
    'getTeam' : IDL.Func([TeamId], [Team], ['query']),
    'getTeamGames' : IDL.Func([TeamId], [IDL.Vec(Game)], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getUpcomingGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };