/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : GameId,
  'status' : GameStatus,
  'awayTeamId' : TeamId,
  'date' : string,
  'time' : string,
  'week' : bigint,
  'homeTeamId' : TeamId,
  'season' : bigint,
  'homeScore' : [] | [bigint],
  'awayScore' : [] | [bigint],
  'location' : string,
}
export type GameId = bigint;
export type GameStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type NewsCategory = { 'teamNews' : null } |
  { 'gameRecap' : null } |
  { 'announcement' : null } |
  { 'leagueUpdate' : null };
export interface NewsPost {
  'id' : NewsPostId,
  'title' : string,
  'content' : string,
  'publishedDate' : Time,
  'author' : string,
  'category' : NewsCategory,
}
export type NewsPostId = bigint;
export interface Standing {
  'pointsFor' : bigint,
  'ties' : bigint,
  'wins' : bigint,
  'conferenceRank' : bigint,
  'division' : string,
  'losses' : bigint,
  'pointsAgainst' : bigint,
  'teamId' : TeamId,
}
export interface Team {
  'id' : TeamId,
  'city' : string,
  'name' : string,
  'ties' : bigint,
  'wins' : bigint,
  'division' : string,
  'losses' : bigint,
  'colors' : { 'secondary' : string, 'primary' : string },
}
export type TeamId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'addNewsPost' : ActorMethod<[NewsPost], undefined>,
  'addUpdateGame' : ActorMethod<[Game], undefined>,
  'addUpdateTeam' : ActorMethod<[Team], undefined>,
  'getCompletedGames' : ActorMethod<[], Array<Game>>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getNews' : ActorMethod<[], Array<NewsPost>>,
  'getNewsPost' : ActorMethod<[NewsPostId], NewsPost>,
  'getStandings' : ActorMethod<[], Array<Standing>>,
  'getTeam' : ActorMethod<[TeamId], Team>,
  'getTeamGames' : ActorMethod<[TeamId], Array<Game>>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'getUpcomingGames' : ActorMethod<[], Array<Game>>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];