/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Team {
    id: TeamId;
    city: string;
    name: string;
    ties: bigint;
    wins: bigint;
    division: string;
    losses: bigint;
    colors: {
        secondary: string;
        primary: string;
    };
}
export interface Game {
    id: GameId;
    status: GameStatus;
    awayTeamId: TeamId;
    date: string;
    time: string;
    week: bigint;
    homeTeamId: TeamId;
    season: bigint;
    homeScore?: bigint;
    awayScore?: bigint;
    location: string;
}
export type Time = bigint;
export type GameId = bigint;
export interface Standing {
    pointsFor: bigint;
    ties: bigint;
    wins: bigint;
    conferenceRank: bigint;
    division: string;
    losses: bigint;
    pointsAgainst: bigint;
    teamId: TeamId;
}
export type NewsPostId = bigint;
export type TeamId = bigint;
export interface NewsPost {
    id: NewsPostId;
    title: string;
    content: string;
    publishedDate: Time;
    author: string;
    category: NewsCategory;
}
export enum GameStatus {
    upcoming = "upcoming",
    completed = "completed",
    inProgress = "inProgress"
}
export enum NewsCategory {
    teamNews = "teamNews",
    gameRecap = "gameRecap",
    announcement = "announcement",
    leagueUpdate = "leagueUpdate"
}
export interface backendInterface {
    addNewsPost(news: NewsPost): Promise<void>;
    addUpdateGame(game: Game): Promise<void>;
    addUpdateTeam(team: Team): Promise<void>;
    getCompletedGames(): Promise<Array<Game>>;
    getGames(): Promise<Array<Game>>;
    getNews(): Promise<Array<NewsPost>>;
    getNewsPost(id: NewsPostId): Promise<NewsPost>;
    getStandings(): Promise<Array<Standing>>;
    getTeam(id: TeamId): Promise<Team>;
    getTeamGames(teamId: TeamId): Promise<Array<Game>>;
    getTeams(): Promise<Array<Team>>;
    getUpcomingGames(): Promise<Array<Game>>;
    initialize(): Promise<void>;
}
import type { Game as _Game, GameId as _GameId, GameStatus as _GameStatus, NewsCategory as _NewsCategory, NewsPost as _NewsPost, NewsPostId as _NewsPostId, TeamId as _TeamId, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNewsPost(arg0: NewsPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsPost(to_candid_NewsPost_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsPost(to_candid_NewsPost_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addUpdateGame(arg0: Game): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpdateGame(to_candid_Game_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpdateGame(to_candid_Game_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addUpdateTeam(arg0: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpdateTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpdateTeam(arg0);
            return result;
        }
    }
    async getCompletedGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedGames();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedGames();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGames();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGames();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNews(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPost(arg0: NewsPostId): Promise<NewsPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPost(arg0);
                return from_candid_NewsPost_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPost(arg0);
            return from_candid_NewsPost_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStandings(): Promise<Array<Standing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandings();
            return result;
        }
    }
    async getTeam(arg0: TeamId): Promise<Team> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return result;
        }
    }
    async getTeamGames(arg0: TeamId): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamGames(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamGames(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return result;
        }
    }
    async getUpcomingGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingGames();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingGames();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
}
function from_candid_GameStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_NewsCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsCategory): NewsCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_NewsPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsPost): NewsPost {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    status: _GameStatus;
    awayTeamId: _TeamId;
    date: string;
    time: string;
    week: bigint;
    homeTeamId: _TeamId;
    season: bigint;
    homeScore: [] | [bigint];
    awayScore: [] | [bigint];
    location: string;
}): {
    id: GameId;
    status: GameStatus;
    awayTeamId: TeamId;
    date: string;
    time: string;
    week: bigint;
    homeTeamId: TeamId;
    season: bigint;
    homeScore?: bigint;
    awayScore?: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_GameStatus_n12(_uploadFile, _downloadFile, value.status),
        awayTeamId: value.awayTeamId,
        date: value.date,
        time: value.time,
        week: value.week,
        homeTeamId: value.homeTeamId,
        season: value.season,
        homeScore: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.homeScore)),
        awayScore: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.awayScore)),
        location: value.location
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NewsPostId;
    title: string;
    content: string;
    publishedDate: _Time;
    author: string;
    category: _NewsCategory;
}): {
    id: NewsPostId;
    title: string;
    content: string;
    publishedDate: Time;
    author: string;
    category: NewsCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedDate: value.publishedDate,
        author: value.author,
        category: from_candid_NewsCategory_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): GameStatus {
    return "upcoming" in value ? GameStatus.upcoming : "completed" in value ? GameStatus.completed : "inProgress" in value ? GameStatus.inProgress : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamNews: null;
} | {
    gameRecap: null;
} | {
    announcement: null;
} | {
    leagueUpdate: null;
}): NewsCategory {
    return "teamNews" in value ? NewsCategory.teamNews : "gameRecap" in value ? NewsCategory.gameRecap : "announcement" in value ? NewsCategory.announcement : "leagueUpdate" in value ? NewsCategory.leagueUpdate : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsPost>): Array<NewsPost> {
    return value.map((x)=>from_candid_NewsPost_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n10(_uploadFile, _downloadFile, x));
}
function to_candid_GameStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): _GameStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Game_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): _Game {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_NewsCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): _NewsCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewsPost_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsPost): _NewsPost {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NewsPostId;
    title: string;
    content: string;
    publishedDate: Time;
    author: string;
    category: NewsCategory;
}): {
    id: _NewsPostId;
    title: string;
    content: string;
    publishedDate: _Time;
    author: string;
    category: _NewsCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedDate: value.publishedDate,
        author: value.author,
        category: to_candid_NewsCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: GameId;
    status: GameStatus;
    awayTeamId: TeamId;
    date: string;
    time: string;
    week: bigint;
    homeTeamId: TeamId;
    season: bigint;
    homeScore?: bigint;
    awayScore?: bigint;
    location: string;
}): {
    id: _GameId;
    status: _GameStatus;
    awayTeamId: _TeamId;
    date: string;
    time: string;
    week: bigint;
    homeTeamId: _TeamId;
    season: bigint;
    homeScore: [] | [bigint];
    awayScore: [] | [bigint];
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_GameStatus_n7(_uploadFile, _downloadFile, value.status),
        awayTeamId: value.awayTeamId,
        date: value.date,
        time: value.time,
        week: value.week,
        homeTeamId: value.homeTeamId,
        season: value.season,
        homeScore: value.homeScore ? candid_some(value.homeScore) : candid_none(),
        awayScore: value.awayScore ? candid_some(value.awayScore) : candid_none(),
        location: value.location
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): {
    teamNews: null;
} | {
    gameRecap: null;
} | {
    announcement: null;
} | {
    leagueUpdate: null;
} {
    return value == NewsCategory.teamNews ? {
        teamNews: null
    } : value == NewsCategory.gameRecap ? {
        gameRecap: null
    } : value == NewsCategory.announcement ? {
        announcement: null
    } : value == NewsCategory.leagueUpdate ? {
        leagueUpdate: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == GameStatus.upcoming ? {
        upcoming: null
    } : value == GameStatus.completed ? {
        completed: null
    } : value == GameStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
